In [1]:
import numpy as np

###  Basics

In [2]:
a = [1, 2, 3]

In [3]:
type(a)

list

In [ ]:
a = np.array([1,2,])
print(a)
type(a)

['1' '2' 'A']


numpy.ndarray

In [8]:
a.dtype

dtype('int16')

In [18]:
type(a[0])

numpy.int16

In [11]:
b = np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [13]:
# Get dimension
a.ndim

1

In [14]:
b.ndim

2

In [15]:
# Get Shape
b.shape

(2, 6)

In [24]:
# Get Type
b.dtype

dtype('int32')

In [16]:
# Get Size
b.itemsize

4

In [26]:
# get total size
a.nbytes

6

### Accessing / Changing specific elements, rows, columns, etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
print(a[1][4])

12


In [36]:
# Get a specific element [r,c]
print(a[1,5])

13


In [37]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [39]:
a[1,5] = 20

# a[0, 1:-1:2]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### 3-D Example

In [40]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [42]:
# Get specific element (work outside in) - 0 channel, first row, first column
b[1,0,1]

6

In [37]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [45]:
# Replace
b[:,1,:] = [[9,9],[8,8]]

In [46]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing different types of Arrays

In [48]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# All 1s in matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [54]:
# Any other number
np.full((3,2), 99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [55]:
# Any other (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.5682528 , 0.56966871],
       [0.15297603, 0.57056527],
       [0.54906777, 0.05111512],
       [0.97566421, 0.27412505]])

In [61]:
# Random Integer values
np.random.randint(9, size=(3,3))

array([[5, 2, 1],
       [4, 1, 1],
       [3, 7, 6]])

In [63]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0 )
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [66]:
a = np.array([1,2,3])
b = a.copy() # just to copy the content only
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [60]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [61]:
a + 2

array([3, 4, 5, 6])

In [62]:
a - 2

array([-1,  0,  1,  2])

In [63]:
a * 2

array([2, 4, 6, 8])

In [64]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [65]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [66]:
a ** 2

array([ 1,  4,  9, 16])

In [67]:
# Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [68]:
np.cos(b)

array([ 0.86231887, -0.41614684, -0.9899925 ])

### Linear Algebra

In [69]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

##### Two matrices are able to multiply if "Columns of first matrix is equal to the rows of the second matix"

In [70]:
# Find the Determinent
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
## Reference docs (https://docs.scipy.org/numpy/reference/routines.linalg.html)

### Statistics

In [72]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.min(stats)

1

In [74]:
np.max(stats, axis=1) # row wise

array([3, 6])

In [75]:
np.sum(stats)

21

### Reorganizing Arrays

In [76]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [77]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Miscellaneous
#### Load Data from File

In [78]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

### Boolean Masking and Advanced Indexing

In [79]:
filedata >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [80]:
filedata[filedata > 5]

array([6., 7., 8.])

In [85]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])

In [86]:
np.any(filedata > 5, axis=0)

array([ True,  True,  True])

In [87]:
((filedata > 5) & (filedata < 7))

array([[False, False, False],
       [ True, False, False]])

In [97]:
~((filedata > 5) & (filedata < 7))

array([[ True,  True,  True,  True, False],
       [ True, False,  True,  True,  True]])

---